### PR TITLE
[JENKINS-35571] Make compatible with Pipeline

### PR DESCRIPTION
**Pull request by vgaidarji**
This PR brings plugin compatibility with Jenkins Pipeline.
Closes [JENKINS-35571](https://issues.jenkins-ci.org/browse/JENKINS-35571).

**Background:**
The work in this PR is based on [MarkusDNC/plot-plugin](https://github.com/MarkusDNC/plot-plugin) repository. That repo contains original plot plugin adjustment for Jenkins Pipeline (works only with Pipeline). In order to not to break compatibility I [diff](https://www.diffchecker.com/diff)'ed every file from modified plugin repo with the original repo. This was a painful process, but since I'm not quite into plot plugin, I decided to go this way since the work was done and I had to combine it with the existing codebase. 
As result, not all changes were applicable on top of existing functionality and I put the difference into `pipeline` package. There might be a better way though.
image

I tried to combine 
`MatrixPlotPublisher`    & `Plot`                            & `MatrixPlotAction` classes with 
`pipeline/PlotPublisher` & `pipeline/PlotBuilder` & `pipeline/PlotAction` but faced incompatibilities and decided to leave those separated.

Additionally, I did some code clean up and fixed PMD warnings.

**Tests**
- Unit tests are passing
- Plot plugin works from Pipeline job
   plot-pipeline
- Plot plugin works from Matrix job
   plot-matrix

TODO:
- [ ] Update plugin docs (add plugin sample usage from Pipeline)
- [ ] Update [Compatibility](https://github.com/jenkinsci/pipeline-plugin/blob/master/COMPATIBILITY.md) document

### CODE REVIEW

**Comment by ericbn** [comment]
This plugin is up for adoption. Want to help improve this plugin? [Click here to learn more!](https://wiki.jenkins-ci.org/display/JENKINS/Adopt+a+Plugin)

**Comment by rtyler** [comment]
@vgaidarji i'm not sure why this isn't rebuilding on ci.jenkins.io now that #31 has been merged. If you close and re-open the pull request, that should trigger a new GitHub webhook event :fire:

**Comment by vgaidarji** [comment]
@rtyler I'm not even sure it should trigger the build as nothing actually changed in this PR.
but yeah, I'll make sure build passes before I merge this one. thanks

**Comment by rtyler** [comment]
YAY, success! :fireworks:

**Comment by svanoort** [comment]
I can't mark it due to lack of repo permissions but I am reviewing (may take a few days to get results)

**Comment by vgaidarji** [comment]
@svanoort I would like to do more clean up in the repo. Would be nice if you start the review in few hours. Basically, no logic change will be done, and clean up will be done in separate commits. We should be fine reviewing commit by commit.

**Comment by vgaidarji** [comment]
Resetting this branch to d2b11f3 and moving clean up activities to separate PR to ease the review and separate concerns.

**Comment by vgaidarji** [comment]
This PR originated from the fork, which was removed.
@svanoort FYI: further steps will be in GH-31.

**Pull request closed without merging**
