### PR TITLE
Add support for minimum and maximum yaxis values

### PR DESCRIPTION
**Pull request by langers2k**
Not sure of the procedure for PR's on this repo. This adds support for manually setting a minimum and maximum for the yaxis values.

### CODE REVIEW

**Comment by langers2k** [comment]
Partial support for https://issues.jenkins-ci.org/browse/JENKINS-2841

**Comment by langers2k** [comment]
Hi @ericbn,

Is it possible to get this reviewed please?

Thanks!

**Comment by vanniktech** [comment]
+1

What's the status on this one?

**Comment by ericbn** [comment]
Thank you for the contribution, @langers2k

**Pull request merged**
