### PR TITLE
Format numbers in the cvs tables, modified table style

### PR DESCRIPTION
**Pull request by radekdoulik**
It improves the CSV data tables visible above the graphs for CVS data series.

The numbers are formatted (i.e. they have thousand separators) and the table style is a bit improved.

### CODE REVIEW

**Comment by vgaidarji** [comment]
@radekdoulik thanks a lot for your contribution 👍 
Could you please review `.github/PULL_REQUEST_TEMPLATE` and add missing details to PR description? It will help to review your change a lot.

**Comment by vgaidarji** [comment]
@radekdoulik thanks a lot for your contribution 👍 
Could you please review `.github/PULL_REQUEST_TEMPLATE` and add missing details to PR description? It will help to review your change a lot.

**Comment by radekdoulik** [comment]
OK, I will try :-)

I will also update the patch a bit, so that it uses `<style>` element in the jelly file.

**Comment by vgaidarji** [comment]
@radekdoulik hey, are you still around? 😃

**Comment by vgaidarji** [comment]
Closing due to inactivity.
@radekdoulik feel free to reopen if it's still actual.

**Comment by radekdoulik** [comment]
Updated the patch and reopened.

**Comment by radekdoulik** [comment]
OK, looks like it didn't reopen. Will create new PR then.

**Pull request closed without merging**
